standardize
workshopper/workshopper-adventure pull request #66
Opened 2016-09-19 23:09 UTC by Flet

Figured I'd just go ahead and do this :)

Closes #62

2016-09-19 23:13 UTC, martinheidegger requested changes
Awesome, but for one thing! Would you mind to add yourself to the contributors?

2016-09-19 23:13 UTC, martinheidegger approved these changes

2016-09-20 04:31 UTC, merged

2016-09-20 04:36 UTC, martinheidegger commented
Should have totally recognised your user, sorry ^_^

2016-09-20 04:39 UTC, Flet commented
No worries, happy to help :)